### ISSUE TITLE
Celestial bodies not behaving properly with orientation/altitude controllers on space station

### ISSUE THREAD

**Issue by AverageUser67** [dercodeKoenig/AdvancedRocketry#19]
## Version of Advanced Rocketry
2.0.1.11

## Have you verified this is an issue in the latest unstable build
- [ ] Y
- [x] N
- [ ] N/A

## Version of ARLib
19062024

## Version of Minecraft
1.12.2 (what other version?)

## Does this occur without other mods installed
- [x] Y
- [ ] N
- [ ] N/A

## Description of the problem
1. go to a space station
2. warp to local star
3. tweak settings on altitude/orientation
4. watch the background but not the star rotate
Also, I noticed that orientation controller does not allow you to stop on non-default orientations, and the X and Y seem to be inverted?? Might want to take a look at that code

https://discord.com/channels/1251616570568867932/1256237646909411450/1258195260501397636

**Comment by AverageUser67** [comment]
The black hole also doesn't respect altitude... ouch

**Comment by dercodeKoenig** [comment]
when orbiting a black hole it should not respect any change in the altitude controller - this is because the scale does not match the size of a black hole. also it would mess up rendering because it might happen that you go inside the sphere when flying too close and the accretion disk would make the entire sky white because it is much brighter now

**Comment by dercodeKoenig** [comment]
fixed in next update
